import { citizenSafetyApi, type EmergencyRecord, type EvacuationRoute } from './api/citizen-safety.api';
import { screenEvacuationRoute, loadRecentUserHazards } from './api/route-screening';
import './responder-routing-enhancer.css';

type LatLng={latitude:number;longitude:number};
type RouteCandidate={distanceM:number;durationS:number;geometry:[number,number][];safetyScore:number;status:'recommended'|'viable'|'rejected';reason:string;rejectionReasons?:string[]};
let selectedIncidentId='';let responderPosition:LatLng|null=null;let candidates:RouteCandidate[]=[];let routing=false;let lastRenderedKey='';
const HANDOFF_KEY='jalrakshak:responder-route-handoff';
const toRad=(v:number)=>v*Math.PI/180;
function haversineMeters(a:LatLng,b:LatLng){const R=6371000,dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude),lat1=toRad(a.latitude),lat2=toRad(b.latitude);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function selectedIdFromDom(){return document.querySelector<HTMLElement>('.ops-id-row > span')?.textContent?.trim()??'';}
function fmtDistance(m:number){return m>=1609.344?`${(m/1609.344).toFixed(1)} mi`:`${Math.max(1,Math.round(m*3.28084))} ft`;}
function fmtDuration(s:number){const min=Math.max(1,Math.round(s/60));return min>=60?`${Math.floor(min/60)}h ${min%60}m`:`${min} min`;}
function persistHandoff(){if(!selectedIncidentId||!responderPosition||!candidates.length)return;sessionStorage.setItem(HANDOFF_KEY,JSON.stringify({incidentId:selectedIncidentId,responderPosition,candidates,updatedAt:new Date().toISOString()}));}
async function persistNavigation(status:'assigned'|'en_route'='assigned',reason:string|null=null){if(!selectedIncidentId||!responderPosition)return;const recommended=candidates.find(r=>r.status==='recommended');if(!recommended)return;await citizenSafetyApi.updateEmergencyNavigation(selectedIncidentId,{responder_latitude:responderPosition.latitude,responder_longitude:responderPosition.longitude,recommended_route:{geometry:recommended.geometry,safety_score:recommended.safetyScore,status:recommended.status,reason:recommended.reason,rejection_reasons:recommended.rejectionReasons??[]},responder_eta_seconds:Math.max(0,Math.round(recommended.durationS)),responder_distance_m:Math.max(0,recommended.distanceM),navigation_status:status,reroute_reason:reason});}
function scoreRoutes(raw:Array<{distanceM:number;durationS:number;geometry:[number,number][]}>,incident:EmergencyRecord):RouteCandidate[]{const risk=Number(incident.risk_score??45),minD=Math.min(...raw.map(r=>r.distanceM)),minT=Math.min(...raw.map(r=>r.durationS));return raw.map(r=>{const dp=Math.min(22,((r.distanceM-minD)/Math.max(minD,1))*18),tp=Math.min(24,((r.durationS-minT)/Math.max(minT,1))*20),ip=risk>=80?8:risk>=60?5:2;return{...r,safetyScore:Math.max(45,Math.round(96-dp-tp-ip)),status:'viable' as const,reason:'Road-route candidate passed basic prototype screening.'};}).sort((a,b)=>b.safetyScore-a.safetyScore||a.durationS-b.durationS).map((r,i)=>({...r,status:i===0?'recommended':'viable',reason:i===0?'Best balance of ETA, distance, and incident-risk context.':'Alternate road route available.'}));}
function screenedCandidates(screened:EvacuationRoute):RouteCandidate[]{return(screened.screened_routes??[]).map(r=>({distanceM:Number(r.distance_m??screened.distance_m),durationS:Number(r.duration_s??screened.duration_s),geometry:(r.geometry??screened.geometry??[]).map(([lat,lon])=>[lon,lat] as [number,number]),safetyScore:Number(r.prototype_safety_score??screened.prototype_safety_score??50),status:r.status,rejectionReasons:r.rejection_reasons??[],reason:r.status==='recommended'?'Safest viable route after hazard screening.':r.status==='rejected'?(r.rejection_reasons?.join(' · ')||'Rejected by hazard screening.'):'Viable alternative after hazard screening.'})).sort((a,b)=>({recommended:0,viable:1,rejected:2}[a.status]-{recommended:0,viable:1,rejected:2}[b.status])||b.safetyScore-a.safetyScore);}
async function fetchRoutes(origin:LatLng,incident:EmergencyRecord):Promise<RouteCandidate[]>{const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),5500);try{const url=`https://router.project-osrm.org/route/v1/driving/${origin.longitude},${origin.latitude};${incident.longitude},${incident.latitude}?alternatives=true&steps=true&overview=full&geometries=geojson`;const response=await fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json() as {routes?:Array<{distance:number;duration:number;geometry?:{coordinates?:[number,number][]}}>};const raw=(data.routes??[]).slice(0,4).map(r=>({distanceM:r.distance,durationS:r.duration,geometry:r.geometry?.coordinates??[]}));if(!raw.length)throw new Error();const base=scoreRoutes(raw,incident),first=base[0];const synthetic:EvacuationRoute={destination_name:`${incident.citizen_name} SOS`,destination_type:'citizen_sos',destination_latitude:incident.latitude,destination_longitude:incident.longitude,distance_m:first.distanceM,duration_s:first.durationS,geometry:first.geometry,steps:[],alternatives_considered:raw.length,prototype_safety_score:first.safetyScore,reasons:['Responder road alternatives generated from OSRM.'],source:'OSRM responder routing',warning:'Prototype rescue routing; verify field conditions.'};const screened=await screenEvacuationRoute(origin.latitude,origin.longitude,synthetic),hazardAware=screenedCandidates(screened);if(screened.screening_status!=='complete')throw new Error('Shared hazard screening unavailable. Retry before dispatch.');return hazardAware;}catch(error){throw error instanceof Error&&error.message?error:new Error('Live road or hazard screening unavailable. Retry before dispatch.');}finally{window.clearTimeout(timer);}}
async function useResponderLocation(){const status=document.querySelector<HTMLElement>('[data-response-route-status]');if(!navigator.geolocation){if(status)status.textContent='Responder GPS is unavailable.';return;}if(status)status.textContent='Locating responder…';navigator.geolocation.getCurrentPosition(async p=>{responderPosition={latitude:p.coords.latitude,longitude:p.coords.longitude};await calculateRoute();},()=>{if(status)status.textContent='Unable to access responder GPS.';},{enableHighAccuracy:true,timeout:9000,maximumAge:3000});}
async function calculateRoute(){if(routing||!responderPosition||!selectedIncidentId)return;routing=true;candidates=[];sessionStorage.removeItem(HANDOFF_KEY);const status=document.querySelector<HTMLElement>('[data-response-route-status]');if(status)status.textContent='Screening road alternatives…';try{const incident=await citizenSafetyApi.getEmergency(selectedIncidentId);candidates=await fetchRoutes(responderPosition,incident);persistHandoff();await persistNavigation(incident.status==='en_route'?'en_route':'assigned','Initial responder route calculated');await render(true);}catch(error){await render(true);const statusNode=document.querySelector<HTMLElement>('[data-response-route-status]');if(statusNode)statusNode.textContent=error instanceof Error?error.message:'Unable to save responder route.';}finally{routing=false;}}
function openLiveRoute(){if(!selectedIncidentId)return;persistHandoff();sessionStorage.setItem('jalrakshak:selected-incident',selectedIncidentId);const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('.ops-nav button'));const liveMap=buttons.find(button=>button.textContent?.includes('Live Map'));liveMap?.click();window.setTimeout(()=>window.dispatchEvent(new CustomEvent('jalrakshak:live-route-opened',{detail:{incidentId:selectedIncidentId}})),80);}
async function render(force=false){const host=document.querySelector<HTMLElement>('.ops-detail-pane'),id=selectedIdFromDom();if(!host||!id){document.querySelector('[data-responder-routing]')?.remove();return;}if(id!==selectedIncidentId){selectedIncidentId=id;candidates=[];responderPosition=null;}let incident:EmergencyRecord;try{incident=await citizenSafetyApi.getEmergency(id);}catch{return;}const recommended=candidates.find(r=>r.status==='recommended'),rejected=candidates.filter(r=>r.status==='rejected').length,viable=candidates.filter(r=>r.status==='viable'||r.status==='recommended').length,key=`${id}|${incident.status}|${candidates.length}|${recommended?.distanceM??0}`;if(!force&&key===lastRenderedKey&&host.querySelector('[data-responder-routing]'))return;lastRenderedKey=key;let panel=host.querySelector<HTMLElement>('[data-responder-routing]');if(!panel){panel=document.createElement('section');panel.dataset.responderRouting='true';panel.className='responder-routing-panel compact';host.querySelector('.ops-main-grid')?.insertAdjacentElement('beforebegin',panel);}if(!panel)return;const reports=loadRecentUserHazards().length;panel.innerHTML=`<div class="compact-route-copy"><span>RESPONDER ROUTE</span><h3>${recommended?'Recommended route ready':candidates.length?'No route recommended':'Route not calculated'}</h3><p data-response-route-status>${recommended?`${candidates.length} analyzed · ${rejected} rejected · ${viable} viable${reports?` · ${reports} report${reports===1?'':'s'} checked`:''}`:candidates.length?'Every available road route was rejected. Recheck conditions.':'Use responder GPS when dispatch is ready.'}</p></div>${recommended?`<div class="compact-route-metrics"><div><span>ETA</span><strong>${fmtDuration(recommended.durationS)}</strong></div><div><span>DISTANCE</span><strong>${fmtDistance(recommended.distanceM)}</strong></div><div><span>SAFETY</span><strong>${recommended.safetyScore}/100</strong></div></div>`:''}<div class="compact-route-actions"><button type="button" data-use-responder-location>${recommended?'RE-SCREEN':'USE RESPONDER GPS'}</button>${recommended?'<button type="button" class="primary" data-open-live-route>OPEN LIVE ROUTE →</button>':''}</div>`;panel.querySelector<HTMLButtonElement>('[data-use-responder-location]')?.addEventListener('click',()=>void useResponderLocation());panel.querySelector<HTMLButtonElement>('[data-open-live-route]')?.addEventListener('click',openLiveRoute);}
let scheduled=false;function scheduleRender(){if(scheduled)return;scheduled=true;window.setTimeout(()=>{scheduled=false;void render();},120);}const observer=new MutationObserver(scheduleRender);const start=()=>{observer.observe(document.body,{childList:true,subtree:true,characterData:true});scheduleRender();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
